# Generated by Django 5.0.1 on 2024-07-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='formulaire_type',
            field=models.BooleanField(default=False),
        ),
    ]
