# Generated by Django 5.0.1 on 2024-07-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0002_formulaire_formulaire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='aides_individuelles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.aidesindividuelles_fp'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='bati',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.bati_f'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='chauffage_eau_chaude',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.chauffageeauchaude_f'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='composition_menage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.compositionmenage_fp'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='descriptif_du_logement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.descriptifdulogement_f'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='financement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.financement_f'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='identification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.identification_f'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='situation_professionnelle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.situationprofessionnelle_fp'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='sondage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.sondage_f'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='ventilation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.ventilation_f'),
        ),
    ]
