# Generated by Django 5.0.1 on 2024-07-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0003_alter_formulaire_aides_individuelles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptifdeslogement_f',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='descriptifdeslogement_f',
            name='numero_du_lot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='descriptifdeslogement_f',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='descriptifdulogement_f',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='descriptifdulogement_f',
            name='numero_du_lot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='descriptifdulogement_f',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='descriptifdulogement_f',
            name='proprietaire_occupant',
            field=models.BooleanField(default=False),
        ),
    ]
