# Generated by Django 5.0.1 on 2024-07-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0004_alter_descriptifdeslogement_f_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionmenage_fp',
            name='nombre_personnes',
            field=models.IntegerField(null=True),
        ),
    ]
