# Generated by Django 5.0.1 on 2024-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0005_alter_compositionmenage_fp_nombre_personnes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidesindividuelles_fp',
            name='nombre_personnes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compositionmenage_fp',
            name='nombre_adultes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compositionmenage_fp',
            name='nombre_enfants_majeurs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compositionmenage_fp',
            name='nombre_enfants_mineurs',
            field=models.IntegerField(null=True),
        ),
    ]
