# Generated by Django 5.0.1 on 2024-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0006_alter_aidesindividuelles_fp_nombre_personnes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidesindividuelles_fp',
            name='aide_anah',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aidesindividuelles_fp',
            name='pret_taux_zero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='travaux_engage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compositionmenage_fp',
            name='personne_handicap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='descriptifdeslogement_f',
            name='proprietaire_occupant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proprietairesoccupantsintro_fp',
            name='difficulte_payer_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proprietairesoccupantsintro_fp',
            name='residence_principale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='situationprofessionnelle_fp',
            name='beneficie_prestation_caf',
            field=models.BooleanField(default=False),
        ),
    ]
