# Generated by Django 5.0.1 on 2024-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0007_alter_aidesindividuelles_fp_aide_anah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidesindividuelles_fp',
            name='menage_bleu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aidesindividuelles_fp',
            name='menage_jaune',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aidesindividuelles_fp',
            name='menage_rose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aidesindividuelles_fp',
            name='menage_violet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aidesindividuelles_fp',
            name='supplement_par_personne',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
