# Generated by Django 5.0.1 on 2024-07-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0009_formulaire_descriptif_des_logement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiseEnPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF')),
                ('docx', models.FileField(blank=True, null=True, upload_to='docx_files/', verbose_name='Document Word')),
                ('formulaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mise_en_page', to='client_form.formulaire', verbose_name='Formulaire associé')),
            ],
        ),
    ]
