# Generated by Django 5.0.1 on 2024-07-21 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0011_remove_aidesindividuelles_fp_menage_bleu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidesIndividuellesQuestionComplementaire_fp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenu_fiscal_foyer', models.FloatField(blank=True, null=True)),
                ('impot_revenu', models.FloatField(blank=True, null=True)),
                ('pret_taux_zero', models.BooleanField(default=False)),
                ('aide_anah', models.BooleanField(default=False)),
                ('montant_aide_anah', models.FloatField(blank=True, null=True)),
                ('annee_aide_anah', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lien_excel', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='logementun_bat',
            name='descriptif_du_logements',
        ),
        migrations.RemoveField(
            model_name='aidesindividuelles_fp',
            name='aide_anah',
        ),
        migrations.RemoveField(
            model_name='aidesindividuelles_fp',
            name='annee_aide_anah',
        ),
        migrations.RemoveField(
            model_name='aidesindividuelles_fp',
            name='impot_revenu',
        ),
        migrations.RemoveField(
            model_name='aidesindividuelles_fp',
            name='montant_aide_anah',
        ),
        migrations.RemoveField(
            model_name='aidesindividuelles_fp',
            name='pret_taux_zero',
        ),
        migrations.RemoveField(
            model_name='aidesindividuelles_fp',
            name='revenu_fiscal_foyer',
        ),
        migrations.AddField(
            model_name='descriptifdeslogement_f',
            name='annee_d_aquisition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptifdeslogement_f',
            name='batiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='descriptifdeslogement_f',
            name='etage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptifdeslogement_f',
            name='nombre_de_piece',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptifdeslogement_f',
            name='surface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='descriptifdulogement_f',
            name='annee_d_aquisition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptifdulogement_f',
            name='etage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptifdulogement_f',
            name='nombre_de_piece',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptifdulogement_f',
            name='surface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='aides_individuelles_question_complementaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.aidesindividuellesquestioncomplementaire_fp'),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='client_form.campagne'),
        ),
        migrations.DeleteModel(
            name='LogementPLS_BAT',
        ),
        migrations.DeleteModel(
            name='LogementUN_BAT',
        ),
    ]
