# Generated by Django 5.0.1 on 2024-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0012_aidesindividuellesquestioncomplementaire_fp_campagne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='clone',
            field=models.BooleanField(default=False),
        ),
    ]
