# Generated by Django 5.0.1 on 2024-07-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0014_alter_formulaire_formulaire_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='lien_excel',
        ),
        migrations.AddField(
            model_name='campagne',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to='excels/'),
        ),
    ]
