# Generated by Django 5.0.1 on 2024-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0015_remove_campagne_lien_excel_campagne_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire',
            name='descriptif_des_logement',
        ),
        migrations.AddField(
            model_name='descriptifdulogement_f',
            name='batiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DescriptifDesLogement_f',
        ),
    ]
