# Generated by Django 5.0.1 on 2024-07-27 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0017_documentcomplementaire_f_alter_campagne_excel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='proprietaires_occupants_intro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.proprietairesoccupantsintro_fp'),
        ),
    ]
