# Generated by Django 5.0.1 on 2024-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0019_remove_descriptifdulogement_f_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bati_f',
            name='chambre1_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='chambre2_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='chambre3_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='chambre4_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='cuisine_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='salle_de_bain_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='sejour1_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='sejour2_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bati_f',
            name='wc_vitrage',
            field=models.CharField(blank=True, choices=[('origne', 'Origne'), ('rénové', 'Rénové')], max_length=6, null=True),
        ),
    ]
