# Generated by Django 5.0.1 on 2024-07-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0021_compositionmenage_fp_infos_supplementaires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentcomplementaire_f',
            name='doc1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentcomplementaire_f',
            name='doc2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentcomplementaire_f',
            name='doc3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentcomplementaire_f',
            name='doc4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentcomplementaire_f',
            name='doc5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='miseenpage',
            name='docx',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Document Word'),
        ),
        migrations.AlterField(
            model_name='miseenpage',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='miseenpage',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR Code'),
        ),
    ]
