# Generated by Django 5.0.1 on 2024-07-31 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0022_alter_campagne_excel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancementSansEcoptz_f',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret_collectif', models.BooleanField(blank=True, default=False, null=True)),
                ('pret_individuel', models.BooleanField(blank=True, default=False, null=True)),
                ('financement_fonds_propres', models.BooleanField(blank=True, default=False, null=True)),
                ('ne_se_prononce_pas', models.BooleanField(blank=True, default=False, null=True)),
                ('duree_pret', models.IntegerField(blank=True, choices=[(3, '3 ans'), (5, '5 ans'), (7, '7 ans'), (10, '10 ans'), (12, '12 ans'), (15, '15 ans'), (20, '20 ans')], null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Financement_f',
            new_name='FinancementAvecEcoptz_f',
        ),
        migrations.RenameField(
            model_name='formulaire',
            old_name='financement',
            new_name='financement_avec_ecoptz',
        ),
        migrations.RenameField(
            model_name='identification_f',
            old_name='address',
            new_name='adresse',
        ),
        migrations.AddField(
            model_name='descriptifdulogement_f',
            name='autre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='identification_f',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='identification_f',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compositionmenage_fp',
            name='situation',
            field=models.CharField(blank=True, choices=[('salarie', 'Salarié'), ('liberal', 'Libéral, indépendant, autoentrepreneur'), ('retraite', 'Retraité'), ('demandeur_emploi', "Demandeur d'emploi"), ('etudiant', 'Etudiant, en formation'), ('autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descriptifdulogement_f',
            name='proprietaire_occupant',
            field=models.CharField(blank=True, choices=[('proprietaire_principale', 'Propriétaire occupant - Résidence principale'), ('proprietaire_secondaire', 'Propriétaire occupant - Résidence secondaire'), ('proprietaire_bailleur', 'Propriétaire bailleur'), ('autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='financement_sans_ecoptz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_form.financementsansecoptz_f'),
        ),
    ]
