# Generated by Django 5.0.1 on 2024-09-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0023_financementsansecoptz_f_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositionmenage_fp',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='financementavececoptz_f',
            name='duree_pret',
        ),
        migrations.RemoveField(
            model_name='financementsansecoptz_f',
            name='duree_pret',
        ),
    ]
