# Generated by Django 5.0.1 on 2024-02-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="identification_number",
            field=models.CharField(default="123456", max_length=6, unique=True),
        ),
    ]
