# Generated by Django 5.0.1 on 2024-03-09 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("description", models.TextField(max_length=400)),
                ("role", models.TextField(max_length=250)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
    ]
